add follow/unfollow functionality
Vonubat/twitter-clone-backend pull request #13
Opened 2023-03-15 15:39 UTC by Kitty-Sam

add follow/unfollow functionality (change User Entity, add follow/unfollow endpoints, add list of migrations without removing previous)

2023-03-15 16:15 UTC, Vonubat requested changes

2023-03-15 16:15 UTC, Vonubat commented on .env.example
Don't delete this file, please. This file will be useful for new users, who will want locally deploy the backend-service.

2023-03-15 16:15 UTC, Vonubat commented on src/config/database-config.ts
So, you need only 1 Migration file (the latest), delete please outdated Migration files.

2023-03-15 16:15 UTC, Vonubat commented on src/migrations/1678887807670-Migartion.ts
This Migration file didn't create all necessary tables (like tweets, likes). It can cause an error for case, when user have empty SQL DB in his/her container. You can fix it as we discussed — kill you container with volume, create container again and than run migration:generate. After that you will get complete Migration file, which will include all nesscary tables

2023-03-15 16:15 UTC, Vonubat commented on src/migrations/1678888075315-Migration.ts
Outdated?

2023-03-15 16:15 UTC, Vonubat commented on src/migrations/1678888528783-Migration.ts
Outdated?

2023-03-15 16:15 UTC, Vonubat commented on src/users/dto/following-user.dto.ts
Add some validation for your dto from class-validator library:
[
![image](https://user-images.githubusercontent.com/59571168/225369572-bb1529e9-2473-456f-8690-da8a423d71ec.png)
](url)

2023-03-15 16:15 UTC, Vonubat commented on src/users/dto/unfollowing-user.dto.ts
The same like in the follow-dto

2023-03-15 16:15 UTC, Vonubat commented on src/users/users.service.ts
Very good, you can a little bit make different HttpException errors messages "User with this id does not exist" for understanding, what kind of user wasn't found. It helps from frontend side easier handle errors.
+ maybe it has sense make check for case when user try to start following himself ^)

2023-03-16 13:47 UTC, skromez requested changes

2023-03-16 13:47 UTC, skromez commented on src/users/users.controller.ts
> +import { UnFollowingDto } from './dto/unfollowing-user.dto';
UnfollowDto

2023-03-16 13:47 UTC, skromez commented on src/users/users.controller.ts
> +    return this.usersService.unFollowingProcess(dto, user);
Unfollow

2023-03-16 13:47 UTC, skromez commented on src/users/users.controller.ts
> +    return this.usersService.unFollowingProcess(dto, user);
I'd call the method just unfollowUser, it's not a process

2023-03-16 13:47 UTC, skromez commented on src/users/users.service.ts
> +  async followingProcess(dto: FollowingDto, user: User) {
I'd call the method just followUser, it's not a process

2023-03-16 13:47 UTC, skromez commented on src/users/users.service.ts
> +    const foundedUser: User | null = await this.userRepository.findOne({
const user, we don't have to explicitly call it founded

2023-03-16 13:47 UTC, skromez commented on src/users/users.service.ts
> +    const foundedUser: User | null = await this.userRepository.findOne({
same as I mentioned above

2023-03-16 14:47 UTC, Vonubat approved these changes

2023-03-16 14:47 UTC, merged